source "https://rubygems.org"

group :jekyll_plugins do
  gem "jekyll-theme-primer"
  gem "jemoji"
  gem "jekyll-avatar"
  gem "jekyll-default-layout"
  gem "jekyll-feed"
  gem "jekyll-mentions"
  gem "jekyll-readme-index"
  gem "jekyll-sitemap"
  gem "jekyll-commonmark-ghpages"
end
